# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    # Fetch all tags
    - name: Fetch all tags
      run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
    # Set up Required Environment
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_13.1.app
      id: tool-select
    # Show Info Xcode version
    - name: Xcode version
      run: /usr/bin/xcodebuild -version
      id: tool-version
    # Perform Tasks: add option `-workspace $PROJECT_NAME.xcworkspace` if you are using cocoapod
    - name: Cleand and Build
      run: xcodebuild -scheme ${{REPLACE_BY_YOUR_SCHEME}} clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator ONLY_ACTIVE_ARCH=YES
